name: Deploy Botpress Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci
        working-directory: my-bot

      - name: Install Botpress CLI
        run: npm i -g @botpress/cli

      - name: Deploy
        run: botpress deploy --path .
        working-directory: my-bot
        env:
          BOTPRESS_TOKEN: ${{ secrets.BOTPRESS_TOKEN }}
          BOTPRESS_WORKSPACE_ID: ${{ secrets.BOTPRESS_WORKSPACE_ID }}
          SUPPORT_API_ENDPOINT: ${{ secrets.SUPPORT_API_ENDPOINT }}

name: Deploy Botpress Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Botpress CLI
        run: npm install -g @botpress/cli

      - name: Log in to Botpress
        env:
          BOTPRESS_TOKEN: ${{ secrets.BOTPRESS_TOKEN }}
        run: bp login --token "$BOTPRESS_TOKEN" --workspaceId "wkspace_01K5S2SMCHM6WYBSX3MW9ZBWFJ"

      - name: Install dependencies
        run: npm ci

      - name: Build the bot
        run: bp build

      - name: Deploy to existing bot
        run: bp deploy --confirm --workspaceId "wkspace_01K5S2SMCHM6WYBSX3MW9ZBWFJ" --botId "43ac4500-8cf8-42ae-b7c4-20de752c6e38"


